import * as angular from 'angular';
export declare let $anchorScroll: angular.IAnchorScrollService;
export declare let $cacheFactory: angular.ICacheFactoryService;
export declare let $compile: angular.ICompileService;
export declare let $controller: angular.IControllerService;
export declare let $document: angular.IDocumentService;
export declare let $exceptionHandler: angular.IExceptionHandlerService;
export declare let $filter: angular.IFilterService;
export declare let $http: angular.IHttpService;
export declare let $httpBackend: angular.IHttpBackendService;
export declare let $httpParamSerializer: angular.IHttpParamSerializer;
export declare let $httpParamSerializerJQLike: any;
export declare let $injector: angular.auto.IInjectorService;
export declare let $interpolate: angular.IInterpolateService;
export declare let $interval: angular.IIntervalService;
export declare let $locale: angular.ILocaleService;
export declare let $location: angular.ILocationService;
export declare let $log: angular.ILogService;
export declare let $parse: angular.IParseService;
export declare let $q: angular.IQService;
export declare let $rootElement: angular.IRootElementService;
export declare let $rootScope: angular.IRootScopeService;
export declare let $sce: angular.ISCEService;
export declare let $sceDelegate: angular.ISCEDelegateService;
export declare let $templateCache: angular.ITemplateCacheService;
export declare let $templateRequest: angular.ITemplateRequestService;
export declare let $timeout: angular.ITimeoutService;
export declare let $window: angular.IWindowService;
export declare let $xhrFactory: any;
export declare function lift(module: angular.IModule): angular.IModule;
export declare function bootstrap(moduleName: string): void;
